### PR TITLE
Move release process from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by dzieciou**

### CODE REVIEW

**Comment by iamrulloh** [comment]
Hi, I saw that release v2.1.1 already published from this action https://github.com/dzieciou/curl-logger/runs/4512160659. But when I want to use it in pom.xml its gives me an error and when I checked it the latest release is still v2.1.0 in maven central repo
```
Could not find artifact com.github.dzieciou.testing:curl-logger:jar:2.1.1 in elasticsearch-releases (https://artifacts.elastic.co/maven)
```

**Comment by dzieciou** [comment]
@iamrulloh Yep, I know, this will be fixed in https://github.com/dzieciou/curl-logger/issues/77. Just give me some time, perhaps over the weekend.

**Comment by iamrulloh** [comment]
Ahh okay. Yup, take ur time and enjoy ur weekend😀

**Comment by dzieciou** [comment]
@iamrulloh Already in Maven Central https://repo1.maven.org/maven2/com/github/dzieciou/testing/curl-logger/2.1.1/

**Comment by iamrulloh** [comment]
Great, thank you!

**Pull request merged**
